#include "ft_printf.h"

int	main(int argc, char const *argv[])
{
	(void)argc;
	(void)argv;
	int count1 = 0;
	int count2 = 0;
	void *front = 0;
	char *s2 = "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus.";
	//printf("\n");
	//ft_printf(" %c %c %c ", 0, 0, 0);
	//ft_printf(" %c %c %c ", '1', '2', '3');
	//ft_printf(" %c %c %c ", '2', '1', 0);
	//printf("\n");
	//printf(" %c %c %c ", 0, 0, 0);
	//printf(" %c %c %c ", '1', '2', '3');
	//printf(" %c %c %c ", '2', '1', 0);
	//printf("\n");
	//ft_printf(" %s %s ", "", "-");
	//ft_printf(" %s %s ", " - ", "");
	//ft_printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	//ft_printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	//printf("\n");
	//printf(" %s %s ", "", "-");
	//printf(" %s %s ", " - ", "");
	//printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	//printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	//printf("\n");
	//ft_printf(" %p %p ", LONG_MIN, LONG_MAX);
	//ft_printf(" %p %p ", INT_MIN, INT_MAX);
	//ft_printf(" %p %p ", ULONG_MAX, -ULONG_MAX);
	//printf("\n");
	//printf(" %p %p ", LONG_MIN, LONG_MAX);
	//printf(" %p %p ", INT_MIN, INT_MAX);
	//printf(" %p %p ", ULONG_MAX, -ULONG_MAX);
	//printf("\n");
	//ft_printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42 ,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	//printf("\n");
	//printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42 ,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	//printf("\n");
	//printf("%d%d%d");
	//printf("\n");
	//ft_printf("%d%d%d");
	//printf("\n");
	//ft_printf("%c%c%c", 'a', '\t', 'b');
	//ft_printf("%cc%cc%c", 'a', '\t', 'b');
	//ft_printf("%cs%cs%c", 'c', 'b', 'a');
	//ft_printf("%s%s%s", "And ", "some", "joined");
	//ft_printf("%s%s%s", "And ", "some", "joined");
	//ft_printf("%ss%ss%ss", "And ", "some other", "joined");
	//ft_printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("\n");
	//ft_printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//ft_printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//ft_printf("%d%dd%d", 1, 2, -3);
	//ft_printf("%d%dd%d", 1, 2, -3);
	//ft_printf("%i%ii%i", 1, 2, -3);
	//ft_printf("%i%ii%i", 1, 2, -3);
	//ft_printf("%u%uu%u", 1, 2, -3);
	//ft_printf("%u%uu%u", 1, 2, -3);
	//ft_printf("%x%xx%x", 1, 2, -3);
	//ft_printf("%x%xx%x", 1, 2, -3);
	//ft_printf("%X%Xx%X", 1, 2, -3);
	//ft_printf("%X%Xx%X", 1, 2, -3);
	//printf("\n");
	//ft_printf("U%dwD Sa*69%p%dJ^iDK\n%s%cv%%%d", 949466078, (void *)756805326971706631, -1799053680, "&(3}Ow<NQ30%4)2j2V", -771951389, 220169056);
	//printf("\n");
	//printf("%c%c%c", 'a', '\t', 'b');
	//printf("%cc%cc%c", 'a', '\t', 'b');
	//printf("%cs%cs%c", 'c', 'b', 'a');
	//printf("%s%s%s", "And ", "some", "joined");
	//printf("%s%s%s", "And ", "some", "joined");
	//printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("\n");
	//printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//printf("%d%dd%d", 1, 2, -3);
	//printf("%d%dd%d", 1, 2, -3);
	//printf("%i%ii%i", 1, 2, -3);
	//printf("%i%ii%i", 1, 2, -3);
	//printf("%u%uu%u", 1, 2, -3);
	//printf("%u%uu%u", 1, 2, -3);
	//printf("%x%xx%x", 1, 2, -3);
	//printf("%x%xx%x", 1, 2, -3);
	//printf("%X%Xx%X", 1, 2, -3);
	//printf("%X%Xx%X", 1, 2, -3);
	//printf("\n");
	//printf("U%dwD Sa*69%p%dJ^iDK\n%s%cv%%%d", 949466078, (void *)756805326971706631, -1799053680, "&(3}Ow<NQ30%4)2j2V", -771951389, 220169056);
	//printf("\n");
	count1 += printf("%p",(void *)0);
	count2 += ft_printf("%p",(void *)0);
	printf("\n");
	printf("\n");
	printf("Head: %s, %d, %p\n", front, front, front);
	printf("\n");
	ft_printf("Head: %s, %d, %p\n", front, front, front);
	printf("\n");
	printf("%i\n%i\n", count1, count2);
}
