#include "ft_printf.h"

int	main(void)
{
	int count1 = 0;
	int count2 = 0;
	void *front = 0;
	char *s2 = "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus.";
	//printf("\n");
	//ft_printf(" %c %c %c ", 0, 0, 0);
	//ft_printf(" %c %c %c ", '1', '2', '3');
	//ft_printf(" %c %c %c ", '2', '1', 0);
	//printf("\n");
	//printf(" %c %c %c ", 0, 0, 0);
	//printf(" %c %c %c ", '1', '2', '3');
	//printf(" %c %c %c ", '2', '1', 0);
	//printf("\n");
	//ft_printf(" %s %s ", "", "-");
	//ft_printf(" %s %s ", " - ", "");
	//ft_printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	//ft_printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	//printf("\n");
	//printf(" %s %s ", "", "-");
	//printf(" %s %s ", " - ", "");
	//printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	//printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	//printf("\n");
	//ft_printf(" %p %p ", LONG_MIN, LONG_MAX);
	//ft_printf(" %p %p ", INT_MIN, INT_MAX);
	//ft_printf(" %p %p ", ULONG_MAX, -ULONG_MAX);
	//printf("\n");
	//printf(" %p %p ", LONG_MIN, LONG_MAX);
	//printf(" %p %p ", INT_MIN, INT_MAX);
	//printf(" %p %p ", ULONG_MAX, -ULONG_MAX);
	//printf("\n");
	//ft_printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42 ,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	//printf("\n");
	//printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42 ,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	//printf("\n");
	//printf("%d%d%d");
	//printf("\n");
	//ft_printf("%d%d%d");
	//printf("\n");
	//ft_printf("%c%c%c", 'a', '\t', 'b');
	//ft_printf("%cc%cc%c", 'a', '\t', 'b');
	//ft_printf("%cs%cs%c", 'c', 'b', 'a');
	//ft_printf("%s%s%s", "And ", "some", "joined");
	//ft_printf("%s%s%s", "And ", "some", "joined");
	//ft_printf("%ss%ss%ss", "And ", "some other", "joined");
	//ft_printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("\n");
	//ft_printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//ft_printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//ft_printf("%d%dd%d", 1, 2, -3);
	//ft_printf("%d%dd%d", 1, 2, -3);
	//ft_printf("%i%ii%i", 1, 2, -3);
	//ft_printf("%i%ii%i", 1, 2, -3);
	//ft_printf("%u%uu%u", 1, 2, -3);
	//ft_printf("%u%uu%u", 1, 2, -3);
	//ft_printf("%x%xx%x", 1, 2, -3);
	//ft_printf("%x%xx%x", 1, 2, -3);
	//ft_printf("%X%Xx%X", 1, 2, -3);
	//ft_printf("%X%Xx%X", 1, 2, -3);
	//printf("\n");
	//ft_printf("U%dwD Sa*69%p%dJ^iDK\n%s%cv%%%d", 949466078, (void *)756805326971706631, -1799053680, "&(3}Ow<NQ30%4)2j2V", -771951389, 220169056);
	//printf("\n");
	//printf("%c%c%c", 'a', '\t', 'b');
	//printf("%cc%cc%c", 'a', '\t', 'b');
	//printf("%cs%cs%c", 'c', 'b', 'a');
	//printf("%s%s%s", "And ", "some", "joined");
	//printf("%s%s%s", "And ", "some", "joined");
	//printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("%ss%ss%ss", "And ", "some other", "joined");
	//printf("\n");
	//printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//printf("%pp\n%p\n%p", (void *)LONG_MAX + 423856, (void *)0, (void *)INT_MAX);
	//printf("\n");
	//printf("%d%dd%d", 1, 2, -3);
	//printf("%d%dd%d", 1, 2, -3);
	//printf("%i%ii%i", 1, 2, -3);
	//printf("%i%ii%i", 1, 2, -3);
	//printf("%u%uu%u", 1, 2, -3);
	//printf("%u%uu%u", 1, 2, -3);
	//printf("%x%xx%x", 1, 2, -3);
	//printf("%x%xx%x", 1, 2, -3);
	//printf("%X%Xx%X", 1, 2, -3);
	//printf("%X%Xx%X", 1, 2, -3);
	//printf("\n");
	//printf("U%dwD Sa*69%p%dJ^iDK\n%s%cv%%%d", 949466078, (void *)756805326971706631, -1799053680, "&(3}Ow<NQ30%4)2j2V", -771951389, 220169056);
	// printf("\n");
	// count1 += printf("%p",(void *)0);
	// count2 += ft_printf("%p",(void *)0);
	// printf("\n");
	// printf("\n");
	// printf("Head: %s, %d, %p\n", front, front, front);
	// printf("\n");
	// ft_printf("Head: %s, %d, %p\n", front, front, front);
	// printf("\n");
	// printf("%i\n%i\n", count1, count2);
	// printf("\n");
	// ft_printf("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
	// printf("\n");
	// printf("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");
	//printf("\n");
	//ft_printf(" %% ");
	//ft_printf(" %%%% ");
	//ft_printf(" %% %% %% ");
	//ft_printf(" %%  %%  %% ");
	//ft_printf(" %%   %%   %% ");
	//ft_printf("%%");
	//ft_printf("%% %%");
	//printf("\n");
	//ft_printf(" %% ");
	//ft_printf(" %%%% ");
	//ft_printf(" %% %% %% ");
	//ft_printf(" %%  %%  %% ");
	//ft_printf(" %%   %%   %% ");
	//ft_printf("%%");
	//ft_printf("%% %%");
	//ft_printf("\n");
	//ft_printf(" %+d ", 0);
	//ft_printf(" %+d ", -1);
	//ft_printf(" %+d ", 9);
	//ft_printf(" %+d ", 10);
	//ft_printf(" %+d ", 11);
	//ft_printf(" %+d ", 15);
	//ft_printf(" %+d ", 16);
	//ft_printf(" %+d ", 17);
	//ft_printf(" %+d ", 99);
	//ft_printf(" %+d ", 100);
	//ft_printf(" %+d ", 101);
	//ft_printf(" %+d ", -9);
	//ft_printf(" %+d ", -10);
	//ft_printf(" %+d ", -11);
	//ft_printf(" %+d ", -14);
	//ft_printf(" %+d ", -15);
	//ft_printf(" %+d ", -16);
	//ft_printf(" %+d ", -99);
	//ft_printf(" %+d ", -100);
	//ft_printf(" %+d ", -101);
	//ft_printf(" %+d ", INT_MAX);
	//ft_printf(" %+d ", INT_MIN);
	//ft_printf(" %+d ", LONG_MAX);
	//ft_printf(" %+d ", LONG_MIN);
	//ft_printf(" %+d ", UINT_MAX);
	//ft_printf(" %+d ", ULONG_MAX);
	//ft_printf(" %+d ", 9223372036854775807LL);
	//ft_printf(" %+d %+d %+d %+d %+d %+d %+d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//ft_printf("\n");
	//ft_printf(" %+i ", 0);
	//ft_printf(" %+i ", -1);
	//ft_printf(" %+i ", 1);
	//ft_printf(" %+i ", 9);
	//ft_printf(" %+i ", 10);
	//ft_printf(" %+i ", 11);
	//ft_printf(" %+i ", 15);
	//ft_printf(" %+i ", 16);
	//ft_printf(" %+i ", 17);
	//ft_printf(" %+i ", 99);
	//ft_printf(" %+i ", 100);
	//ft_printf(" %+i ", 101);
	//ft_printf(" %+i ", -9);
	//ft_printf(" %+i ", -10);
	//ft_printf(" %+i ", -11);
	//ft_printf(" %+i ", -14);
	//ft_printf(" %+i ", -15);
	//ft_printf(" %+i ", -16);
	//ft_printf(" %+i ", -99);
	//ft_printf(" %+i ", -100);
	//ft_printf(" %+i ", -101);
	//ft_printf(" %+i ", INT_MAX);
	//ft_printf(" %+i ", INT_MIN);
	//ft_printf(" %+i ", LONG_MAX);
	//ft_printf(" %+i ", LONG_MIN);
	//ft_printf(" %+i ", UINT_MAX);
	//ft_printf(" %+i ", ULONG_MAX);
	//ft_printf(" %+i ", 9223372036854775807LL);
	//ft_printf(" %+i %+i %+i %+i %+i %+i %+i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf("\n");
	//printf(" %+d ", 0);
	//printf(" %+d ", -1);
	//printf(" %+d ", 9);
	//printf(" %+d ", 10);
	//printf(" %+d ", 11);
	//printf(" %+d ", 15);
	//printf(" %+d ", 16);
	//printf(" %+d ", 17);
	//printf(" %+d ", 99);
	//printf(" %+d ", 100);
	//printf(" %+d ", 101);
	//printf(" %+d ", -9);
	//printf(" %+d ", -10);
	//printf(" %+d ", -11);
	//printf(" %+d ", -14);
	//printf(" %+d ", -15);
	//printf(" %+d ", -16);
	//printf(" %+d ", -99);
	//printf(" %+d ", -100);
	//printf(" %+d ", -101);
	//printf(" %+d ", INT_MAX);
	//printf(" %+d ", INT_MIN);
	//printf(" %+d ", LONG_MAX);
	//printf(" %+d ", LONG_MIN);
	//printf(" %+d ", UINT_MAX);
	//printf(" %+d ", ULONG_MAX);
	//printf(" %+d ", 9223372036854775807LL);
	//printf(" %+d %+d %+d %+d %+d %+d %+d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf("\n");
	//printf(" %+i ", 0);
	//printf(" %+i ", -1);
	//printf(" %+i ", 1);
	//printf(" %+i ", 9);
	//printf(" %+i ", 10);
	//printf(" %+i ", 11);
	//printf(" %+i ", 15);
	//printf(" %+i ", 16);
	//printf(" %+i ", 17);
	//printf(" %+i ", 99);
	//printf(" %+i ", 100);
	//printf(" %+i ", 101);
	//printf(" %+i ", -9);
	//printf(" %+i ", -10);
	//printf(" %+i ", -11);
	//printf(" %+i ", -14);
	//printf(" %+i ", -15);
	//printf(" %+i ", -16);
	//printf(" %+i ", -99);
	//printf(" %+i ", -100);
	//printf(" %+i ", -101);
	//printf(" %+i ", INT_MAX);
	//printf(" %+i ", INT_MIN);
	//printf(" %+i ", LONG_MAX);
	//printf(" %+i ", LONG_MIN);
	//printf(" %+i ", UINT_MAX);
	//printf(" %+i ", ULONG_MAX);
	//printf(" %+i ", 9223372036854775807LL);
	//printf(" %+i %+i %+i %+i %+i %+i %+i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	//printf("\n");
	//printf("%c", '0');
	//printf(" %c ", '0');
	//printf(" %c", '0' - 256);
	//printf("%c ", '0' + 256);
	//printf(" %c %c %c ", '0', 0, '1');
	//printf(" %c %c %c ", ' ', ' ', ' ');
	//printf(" %c %c %c ", '1', '2', '3');
	//printf(" %c %c %c ", '2', '1', 0);
	//printf(" %c %c %c ", 0, '1', '2');
	//printf("\n");
	//ft_printf("%c", '0');
	//ft_printf(" %c ", '0');
	//ft_printf(" %c", '0' - 256);
	//ft_printf("%c ", '0' + 256);
	//ft_printf(" %c %c %c ", '0', 0, '1');
	//ft_printf(" %c %c %c ", ' ', ' ', ' ');
	//ft_printf(" %c %c %c ", '1', '2', '3');
	//ft_printf(" %c %c %c ", '2', '1', 0);
	//ft_printf(" %c %c %c ", 0, '1', '2');
	//printf("\n");
	// ft_printf(" %d ", 0);
	// ft_printf(" %d ", -1);
	// ft_printf(" %d ", 1);
	// ft_printf(" %d ", 9);
	// ft_printf(" %d ", 10);
	// ft_printf(" %d ", 11);
	// ft_printf(" %d ", 15);
	// ft_printf(" %d ", 16);
	// ft_printf(" %d ", 17);
	// ft_printf(" %d ", 99);
	// ft_printf(" %d ", 100);
	// ft_printf(" %d ", 101);
	// ft_printf(" %d ", -9);
	// ft_printf(" %d ", -10);
	// ft_printf(" %d ", -11);
	// ft_printf(" %d ", -14);
	// ft_printf(" %d ", -15);
	// ft_printf(" %d ", -16);
	// ft_printf(" %d ", -99);
	// ft_printf(" %d ", -100);
	// ft_printf(" %d ", -101);
	// ft_printf(" %d ", INT_MAX);
	// ft_printf(" %d ", INT_MIN);
	// ft_printf(" %d ", LONG_MAX);
	// ft_printf(" %d ", LONG_MIN);
	// ft_printf(" %d ", UINT_MAX);
	// ft_printf(" %d ", ULONG_MAX);
	// ft_printf(" %d ", 9223372036854775807LL);
	// ft_printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n");
	// printf(" %d ", 0);
	// printf(" %d ", -1);
	// printf(" %d ", 1);
	// printf(" %d ", 9);
	// printf(" %d ", 10);
	// printf(" %d ", 11);
	// printf(" %d ", 15);
	// printf(" %d ", 16);
	// printf(" %d ", 17);
	// printf(" %d ", 99);
	// printf(" %d ", 100);
	// printf(" %d ", 101);
	// printf(" %d ", -9);
	// printf(" %d ", -10);
	// printf(" %d ", -11);
	// printf(" %d ", -14);
	// printf(" %d ", -15);
	// printf(" %d ", -16);
	// printf(" %d ", -99);
	// printf(" %d ", -100);
	// printf(" %d ", -101);
	// printf(" %d ", INT_MAX);
	// printf(" %d ", INT_MIN);
	// printf(" %d ", LONG_MAX);
	// printf(" %d ", LONG_MIN);
	// printf(" %d ", UINT_MAX);
	// printf(" %d ", ULONG_MAX);
	// printf(" %d ", 9223372036854775807LL);
	// printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n");
	// ft_printf(" %u ", 0);
	// ft_printf(" %u ", -1);
	// ft_printf(" %u ", 1);
	// ft_printf(" %u ", 9);
	// ft_printf(" %u ", 10);
	// ft_printf(" %u ", 11);
	// ft_printf(" %u ", 15);
	// ft_printf(" %u ", 16);
	// ft_printf(" %u ", 17);
	// ft_printf(" %u ", 99);
	// ft_printf(" %u ", 100);
	// ft_printf(" %u ", 101);
	// ft_printf(" %u ", -9);
	// ft_printf(" %u ", -10);
	// ft_printf(" %u ", -11);
	// ft_printf(" %u ", -14);
	// ft_printf(" %u ", -15);
	// ft_printf(" %u ", -16);
	// ft_printf(" %u ", -99);
	// ft_printf(" %u ", -100);
	// ft_printf(" %u ", -101);
	// ft_printf(" %u ", INT_MAX);
	// ft_printf(" %u ", INT_MIN);
	// ft_printf(" %u ", LONG_MAX);
	// ft_printf(" %u ", LONG_MIN);
	// ft_printf(" %u ", UINT_MAX);
	// ft_printf(" %u ", ULONG_MAX);
	// ft_printf(" %u ", 9223372036854775807LL);
	// ft_printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n");
	// printf(" %u ", 0);
	// printf(" %u ", -1);
	// printf(" %u ", 1);
	// printf(" %u ", 9);
	// printf(" %u ", 10);
	// printf(" %u ", 11);
	// printf(" %u ", 15);
	// printf(" %u ", 16);
	// printf(" %u ", 17);
	// printf(" %u ", 99);
	// printf(" %u ", 100);
	// printf(" %u ", 101);
	// printf(" %u ", -9);
	// printf(" %u ", -10);
	// printf(" %u ", -11);
	// printf(" %u ", -14);
	// printf(" %u ", -15);
	// printf(" %u ", -16);
	// printf(" %u ", -99);
	// printf(" %u ", -100);
	// printf(" %u ", -101);
	// printf(" %u ", INT_MAX);
	// printf(" %u ", INT_MIN);
	// printf(" %u ", LONG_MAX);
	// printf(" %u ", LONG_MIN);
	// printf(" %u ", UINT_MAX);
	// printf(" %u ", ULONG_MAX);
	// printf(" %u ", 9223372036854775807LL);
	// printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	// printf("\n");
	// printf(" %  i", 11);
	// ft_printf(" %  i", 11);
}
